[workspace]
authors = ["RadishJin <radishj24@gmail.com>"]
channels = ["conda-forge"]
name = "RADtoolkit"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
biotite = ">=1.7.1,<2"
numpy = ">=2.3.5,<3"
pandas = ">=3.0.6,<4"
python = "3.12.*"
pytorch = ">=2.13.0,<3"
biopython = ">=1.88,<2"
